import type { WhiteLabelConfig } from './types';

export const amerisBank: WhiteLabelConfig = {
  slug: 'ameris-bank',
  defaultFlows: ['rate_range', 'full_application', 'data_only'],
  branding: {
    name: 'Ameris Bank',
    shortName: 'Ameris',
    wordmark: 'AMERIS BANK',
    tagline: 'We Mean Business',
    primary: '#1a5c7e',
    primaryDark: '#124257',
    accent: '#d4a843',
    bg: '#f5f7fa',
    surface: '#ffffff',
    text: '#16202e',
    textMuted: '#5b6677',
    border: '#dde3ea',
    font: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    googleFont: 'Inter',
    radius: '6px',
  },
  purposes: [
    { value: 'buy-home', label: 'Buy or refinance a home' },
    { value: 'build-home', label: 'Build a home or buy land' },
    { value: 'home-improvement', label: 'Home improvement or renovation' },
    { value: 'debt-consolidation', label: 'Consolidate debt' },
    { value: 'major-purchase', label: 'A major purchase or expense' },
    { value: 'auto', label: 'Finance a vehicle' },
    { value: 'business', label: 'Grow my business' },
  ],
  products: [
    {
      id: 'mortgage',
      type: 'mortgage',
      label: 'Home Mortgage',
      blurb: 'Fixed and adjustable-rate home loans, locally underwritten and in-house serviced across the Southeast.',
      iconPath: 'M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z M9 22V12h6v10',
      minAmount: 50000,
      maxAmount: 1500000,
      defaultAmount: 275000,
      purposes: ['buy-home'],
      rateTeaser: 'Fixed rates from 6.49% APR',
      disclosure: 'Rates shown are illustrative estimates for this demo, not an offer of credit. Subject to credit approval and property appraisal.',
    },
    {
      id: 'heloc',
      type: 'heloc',
      label: 'Home Equity Line of Credit',
      blurb: 'Tap your equity for home improvements, major expenses, or debt consolidation — interest only on what you use.',
      iconPath: 'M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z M9 22V12h6v10',
      minAmount: 10000,
      maxAmount: 300000,
      defaultAmount: 50000,
      purposes: ['home-improvement', 'debt-consolidation', 'major-purchase'],
      rateTeaser: 'Variable rates from 7.74% APR',
      disclosure: 'Rates shown are illustrative estimates for this demo, not an offer of credit. Subject to credit approval and property appraisal.',
    },
    {
      id: 'home-equity',
      type: 'home-equity',
      label: 'Home Equity Loan',
      blurb: 'A fixed lump sum at a fixed rate against your home equity, with predictable monthly payments.',
      iconPath: 'M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z M9 22V12h6v10',
      minAmount: 10000,
      maxAmount: 250000,
      defaultAmount: 40000,
      purposes: ['home-improvement', 'debt-consolidation', 'major-purchase'],
      rateTeaser: 'Fixed rates from 8.24% APR',
      disclosure: 'Rates shown are illustrative estimates for this demo, not an offer of credit. Subject to credit approval and property appraisal.',
    },
    {
      id: 'personal',
      type: 'personal',
      label: 'Personal Loan',
      blurb: 'Unsecured personal loans for any purpose — medical, travel, or unexpected expenses — with a local decision.',
      iconPath: 'M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2 M12 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8z',
      minAmount: 1000,
      maxAmount: 50000,
      defaultAmount: 15000,
      purposes: ['major-purchase', 'debt-consolidation'],
      rateTeaser: 'Fixed rates from 9.99% APR',
      disclosure: 'Rates shown are illustrative estimates for this demo, not an offer of credit. Subject to credit approval.',
    },
    {
      id: 'auto',
      type: 'auto',
      label: 'Auto Loan',
      blurb: 'New or used vehicle financing with competitive rates and a fast local decision.',
      iconPath: 'M5 17H3a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v5 M16 17H9 M11 21a2 2 0 1 0 0-4 2 2 0 0 0 0 4 M18 21a2 2 0 1 0 0-4 2 2 0 0 0 0 4',
      minAmount: 5000,
      maxAmount: 100000,
      defaultAmount: 32000,
      purposes: ['major-purchase'],
      rateTeaser: 'Rates from 6.74% APR',
      disclosure: 'Rates shown are illustrative estimates for this demo, not an offer of credit. Subject to credit approval.',
    },
    {
      id: 'business',
      type: 'business',
      label: 'Commercial & Business Lending',
      blurb: 'Commercial real estate, operating lines, equipment, and SBA loans for businesses across the Southeast.',
      iconPath: 'M3 21h18 M5 21V7l8-4v18 M19 21V11l-6-3 M9 9v.01 M9 12v.01 M9 15v.01',
      minAmount: 25000,
      maxAmount: 5000000,
      defaultAmount: 250000,
      purposes: ['business'],
      rateTeaser: 'Custom commercial pricing',
      disclosure: 'Commercial requests are routed to a relationship manager after verification.',
    },
  ],
  providerRouting: {
    mortgage: [
      { module: 'identity', provider: 'Socure', label: 'Verifying your identity' },
      { module: 'financial', provider: 'Plaid', label: 'Connecting your bank account', interactive: true },
      { module: 'employment', provider: 'Truework', label: 'Verifying income & employment' },
      { module: 'residence', provider: 'Melissa', label: 'Pulling property details' },
      { module: 'credit', provider: 'Experian', label: 'Checking your credit profile' },
    ],
    heloc: [
      { module: 'identity', provider: 'Socure', label: 'Verifying your identity' },
      { module: 'financial', provider: 'Plaid', label: 'Connecting your bank account', interactive: true },
      { module: 'employment', provider: 'Truework', label: 'Verifying income & employment' },
      { module: 'residence', provider: 'Melissa', label: 'Valuing your property' },
      { module: 'credit', provider: 'Experian', label: 'Checking your credit profile' },
    ],
    'home-equity': [
      { module: 'identity', provider: 'Socure', label: 'Verifying your identity' },
      { module: 'financial', provider: 'Plaid', label: 'Connecting your bank account', interactive: true },
      { module: 'employment', provider: 'Truework', label: 'Verifying income & employment' },
      { module: 'residence', provider: 'Melissa', label: 'Valuing your property' },
      { module: 'credit', provider: 'Experian', label: 'Checking your credit profile' },
    ],
    personal: [
      { module: 'identity', provider: 'Socure', label: 'Verifying your identity' },
      { module: 'financial', provider: 'Plaid', label: 'Connecting your bank account', interactive: true },
      { module: 'employment', provider: 'Truework', label: 'Verifying income & employment' },
      { module: 'credit', provider: 'Experian', label: 'Checking your credit profile' },
    ],
    auto: [
      { module: 'identity', provider: 'Socure', label: 'Verifying your identity' },
      { module: 'financial', provider: 'Plaid', label: 'Connecting your bank account', interactive: true },
      { module: 'employment', provider: 'Truework', label: 'Verifying income & employment' },
      { module: 'credit', provider: 'Experian', label: 'Checking your credit profile' },
    ],
    business: [
      { module: 'identity', provider: 'Socure', label: 'Verifying owner identity' },
      { module: 'contact', provider: 'FullContact', label: 'Confirming business contact' },
      { module: 'financial', provider: 'Plaid', label: 'Connecting your business accounts', interactive: true },
      { module: 'credit', provider: 'Experian', label: 'Checking credit profile' },
    ],
  },
  rateCard: {
    mortgage: {
      defaultTermMonths: 360,
      tiers: [
        { label: 'Excellent credit', minScore: 760, maxLtv: 0.8, terms: [
          { termMonths: 180, apr: 0.0649 }, { termMonths: 240, apr: 0.0674 }, { termMonths: 360, apr: 0.0699 },
        ] },
        { label: 'Strong credit', minScore: 720, maxLtv: 0.9, terms: [
          { termMonths: 180, apr: 0.0699 }, { termMonths: 240, apr: 0.0724 }, { termMonths: 360, apr: 0.0749 },
        ] },
        { label: 'Good credit', minScore: 680, maxLtv: 0.95, terms: [
          { termMonths: 180, apr: 0.0774 }, { termMonths: 240, apr: 0.0799 }, { termMonths: 360, apr: 0.0824 },
        ] },
      ],
      fallbackTerms: [
        { termMonths: 180, apr: 0.0924 }, { termMonths: 240, apr: 0.0949 }, { termMonths: 360, apr: 0.0974 },
      ],
    },
    heloc: {
      defaultTermMonths: 180,
      tiers: [
        { label: 'Excellent credit, low LTV', minScore: 760, maxLtv: 0.7, terms: [
          { termMonths: 120, apr: 0.0774 }, { termMonths: 180, apr: 0.0799 }, { termMonths: 240, apr: 0.0824 },
        ] },
        { label: 'Strong credit', minScore: 720, maxLtv: 0.8, terms: [
          { termMonths: 120, apr: 0.0849 }, { termMonths: 180, apr: 0.0874 }, { termMonths: 240, apr: 0.0899 },
        ] },
        { label: 'Good credit', minScore: 680, maxLtv: 0.85, terms: [
          { termMonths: 120, apr: 0.0974 }, { termMonths: 180, apr: 0.0999 }, { termMonths: 240, apr: 0.1024 },
        ] },
      ],
      fallbackTerms: [
        { termMonths: 120, apr: 0.1124 }, { termMonths: 180, apr: 0.1149 }, { termMonths: 240, apr: 0.1174 },
      ],
    },
    'home-equity': {
      defaultTermMonths: 180,
      tiers: [
        { label: 'Excellent credit, low LTV', minScore: 760, maxLtv: 0.7, terms: [
          { termMonths: 60, apr: 0.0824 }, { termMonths: 120, apr: 0.0849 }, { termMonths: 180, apr: 0.0874 }, { termMonths: 240, apr: 0.0899 },
        ] },
        { label: 'Strong credit', minScore: 720, maxLtv: 0.8, terms: [
          { termMonths: 60, apr: 0.0899 }, { termMonths: 120, apr: 0.0924 }, { termMonths: 180, apr: 0.0949 }, { termMonths: 240, apr: 0.0974 },
        ] },
        { label: 'Good credit', minScore: 680, maxLtv: 0.85, terms: [
          { termMonths: 60, apr: 0.1024 }, { termMonths: 120, apr: 0.1049 }, { termMonths: 180, apr: 0.1074 }, { termMonths: 240, apr: 0.1099 },
        ] },
      ],
      fallbackTerms: [
        { termMonths: 60, apr: 0.1174 }, { termMonths: 120, apr: 0.1199 }, { termMonths: 180, apr: 0.1224 }, { termMonths: 240, apr: 0.1249 },
      ],
    },
  },
  coreSync: {
    system: 'fis',
    displayName: 'FIS',
    mode: 'mock',
  },
  loTeam: {
    name: 'Ameris Bank Lending',
    title: 'Mortgage & Consumer Lending',
  },
};
